config/routes.rb
Rails.application.routes.draw do

    root 'users#new'

    resources :users, except: [:new] do
      resources :resumes
    end

    # get '/users' => 'users#index' #Will bring you to an index of every user registered
    get '/signup' => 'users#new'
    # post "/users" => "users#create"
    # get 'users/:id' => 'users#show', as: :user
    # get 'users/:id/edit' => 'users#edit', as: :edit_user
    # put 'users/:id' => 'users#update'
    # delete 'users/:id' => 'users#destroy'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    # get 'users/:user_id/resumes/' => 'resumes#index'
    # get 'users/:user_id/resumes/new' => 'resumes#new'
    # post 'users/:user_id/resumes/create' => 'resumes#create'
    # get 'users/:user_id/resumes/:id' => 'resumes#show'
    # get 'users/:user_id/resumes/:id/edit' => 'resumes#edit'
    # put 'resumes/:id' => 'resumes#update'
    # delete 'resumes/:id' => 'resumes#destroy'

    ## Rando pages
    get '/welcome' => 'static#welcome'

end

app/models/resume.rb
class Resume < ActiveRecord::Base

    belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

    has_secure_password

    has_many :resumes

    # def admin?
    #     self.role == "admin"
    # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
helper_method :current_user, :authorize, :require_admin

include ApplicationHelper

def current_user

     if session[:user_id]
         @current_user ||= User.find(session[:user_id])
         return @current_user
     else
         return nil
     end
 end

 def authorize
   redirect_to '/login' unless current_user
 end

 def require_admin
     redirect_to '/login' unless current_user.admin
 end


end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
# before_filter :authorize

  def index
    @user = User.find(params[:user_id])
    @resumes = @user.resumes.all
  end

  def new
     @user = current_user
     @resume = @user.resumes.build
  end

  def create
    @resume = current_user.resumes.build(resume_params)
    if @resume.save
      redirect_to '/'
    else
      render "new"
    end
  end

  def show
    @resume = Resume.find(params[:id])
  end

 def edit
    @user = current_user
    @resume = @user.resumes.find(params[:id])
  end

  def update
    @resume = Resume.find(params[:id])
      if @resume.update_attributes(resume_params)
        redirect_to 'user_resumes'
      else
        render "edit"
      end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to user_resumes_path
  end

  private
    def resume_params
      params.require(:resume).permit(:education_1, :education_1_school, :education_1_degree, :education_1_major, :education_1_minor, :education_1_duration, :education_2, :education_2_degree, :education_2_major, :education_2_minor, :education_2_duration, :education_3, :education_3_degree, :education_3_major, :education_3_minor, :education_3_duration, :experience_1, :experience_1_position, :experience_1_duration, :experience_1_description, :experience_2, :experience_2_position, :experience_2_duration, :experience_2_description, :experience_3, :experience_3_position, :experience_3_duration, :experience_3_description, :experience_4, :experience_4_position, :experience_4_duration, :experience_4_description, :skills_description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by_email(params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to '/welcome'
        else
            redirect_to '/login'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to '/'
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    def index
    end

    def welcome
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to users_path
      else
        render "new"
      end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        redirect_to users_path
      else
        render "edit"
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

#Adds typekit helper
    def typekit_include_tag apikey
      javascript_include_tag("http://use.typekit.com/ruq7dqb.js") +
      javascript_tag("try{Typekit.load()}catch(e){}")
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
        redirect_to '/login' unless current_user
    end

end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= typekit 'ruq7dqb' %>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Epitome</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
Currently logged in as <%= current_user.email %> <%= link_to "logout", logout_path %>
<% else %>
Logged out, mofo
<% end %>





<%= yield %>

</body>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/edit.html.erb
<h1>Edit a page</h1>
<p>Find me in app/views/resumes/edit.html.erb</p>

<%= form_for [@user, @resume] do |f| %>

<%= f.label :education_1 %>:
  <%= f.text_field :education_1 %><br />

  <%= f.label :education_1_degree %>:
  <%= f.text_field :education_1_degree %><br />

  <%= f.label :education_1_major %>:
  <%= f.text_field :education_1_major %><br />

  <%= f.label :education_1_minor %>:
  <%= f.text_field :education_1_minor %><br />

  <%= f.label :education_1_duration %>:
  <%= f.text_field :education_1_duration %><br />

<%= f.label :education_2 %>:
  <%= f.text_field :education_2 %><br />

  <%= f.label :education_2_degree %>:
  <%= f.text_field :education_2_degree %><br />

  <%= f.label :education_2_major %>:
  <%= f.text_field :education_2_major %><br />

  <%= f.label :education_2_minor %>:
  <%= f.text_field :education_2_minor %><br />

    <%= f.label :education_2_duration %>:
  <%= f.text_field :education_2_duration %><br />

<%= f.label :education_3 %>:
    <%= f.text_field :education_3 %><br />

  <%= f.label :education_3_degree %>:
  <%= f.text_field :education_3_degree %><br />

  <%= f.label :education_3_major %>:
  <%= f.text_field :education_3_major %><br />

  <%= f.label :education_3_minor %>:
  <%= f.text_field :education_3_minor %><br />

    <%= f.label :education_3_duration %>:
  <%= f.text_field :education_3_duration %><br />

<%= f.label :experience_1 %>:
    <%= f.text_field :experience_1 %><br />

  <%= f.label :experience_1_position %>:
  <%= f.text_field :experience_1_position %><br />

  <%= f.label :experience_1_duration %>:
  <%= f.text_field :experience_1_duration %><br />

  <%= f.label :experience_1_description %>:
  <%= f.text_area :experience_1_description %><br />

<%= f.label :experience_2 %>:
    <%= f.text_field :experience_2 %><br />

  <%= f.label :experience_2_position %>:
  <%= f.text_field :experience_2_position %><br />

  <%= f.label :experience_2_duration %>:
  <%= f.text_field :experience_2_duration %><br />

  <%= f.label :experience_2_description %>:
  <%= f.text_area :experience_2_description %><br />

  <%= f.label :experience_3 %>:
    <%= f.text_field :experience_3 %><br />

  <%= f.label :experience_3_position %>:
  <%= f.text_field :experience_3_position %><br />

  <%= f.label :experience_3_duration %>:
  <%= f.text_field :experience_3_duration %><br />

  <%= f.label :experience_3_description %>:
  <%= f.text_area :experience_3_description %><br />

<%= f.label :experience_4 %>:
    <%= f.text_field :experience_4 %><br />

  <%= f.label :experience_4_position %>:
  <%= f.text_field :experience_4_position %><br />

  <%= f.label :experience_4_duration %>:
  <%= f.text_field :experience_4_duration %><br />

  <%= f.label :experience_4_description %>:
  <%= f.text_area :experience_4_description %><br />

  <%= f.label :skills_description %>:
  <%= f.text_area :skills_description %><br />

  <%= f.submit "Edit" %>
  <% end %>

app/views/resumes/index.html.erb
<h1>Resumes#index</h1>
<p>Find me in app/views/resumes/index.html.erb</p>

<ul>
    <% @resumes.each do |r| %>
        <li><%= r.education_1 %></li>
        <li><%= r.education_1_degree %></li>
        <li><%= link_to "edit", edit_user_resume_path(current_user, r) %></li>
        <li><%= link_to "delete this resume", user_resume_path(current_user, r), method: :delete %></li>
 <!--        method: :delete %></li> -->
        <hr>
    <% end %>
</ul>

<%= link_to "sign up", signup_path %>

app/views/resumes/new.html.erb
<h1>Resumes#new</h1>
<p>Let's great a new resume! Hopefully this works!</p>


<%= form_for [@user, @resume] do |f| %>
<%= f.label :education_1 %>:
  <%= f.text_field :education_1 %><br />

  <%= f.label :education_1_degree %>:
  <%= f.text_field :education_1_degree %><br />

  <%= f.label :education_1_major %>:
  <%= f.text_field :education_1_major %><br />

  <%= f.label :education_1_minor %>:
  <%= f.text_field :education_1_minor %><br />

  <%= f.label :education_1_duration %>:
  <%= f.text_field :education_1_duration %><br />

<%= f.label :education_2 %>:
  <%= f.text_field :education_2 %><br />

  <%= f.label :education_2_degree %>:
  <%= f.text_field :education_2_degree %><br />

  <%= f.label :education_2_major %>:
  <%= f.text_field :education_2_major %><br />

  <%= f.label :education_2_minor %>:
  <%= f.text_field :education_2_minor %><br />

    <%= f.label :education_2_duration %>:
  <%= f.text_field :education_2_duration %><br />

<%= f.label :education_3 %>:
    <%= f.text_field :education_3 %><br />

  <%= f.label :education_3_degree %>:
  <%= f.text_field :education_3_degree %><br />

  <%= f.label :education_3_major %>:
  <%= f.text_field :education_3_major %><br />

  <%= f.label :education_3_minor %>:
  <%= f.text_field :education_3_minor %><br />

    <%= f.label :education_3_duration %>:
  <%= f.text_field :education_3_duration %><br />

<%= f.label :experience_1 %>:
    <%= f.text_field :experience_1 %><br />

  <%= f.label :experience_1_position %>:
  <%= f.text_field :experience_1_position %><br />

  <%= f.label :experience_1_duration %>:
  <%= f.text_field :experience_1_duration %><br />

  <%= f.label :experience_1_description %>:
  <%= f.text_area :experience_1_description %><br />

<%= f.label :experience_2 %>:
    <%= f.text_field :experience_2 %><br />

  <%= f.label :experience_2_position %>:
  <%= f.text_field :experience_2_position %><br />

  <%= f.label :experience_2_duration %>:
  <%= f.text_field :experience_2_duration %><br />

  <%= f.label :experience_2_description %>:
  <%= f.text_area :experience_2_description %><br />

  <%= f.label :experience_3 %>:
    <%= f.text_field :experience_3 %><br />

  <%= f.label :experience_3_position %>:
  <%= f.text_field :experience_3_position %><br />

  <%= f.label :experience_3_duration %>:
  <%= f.text_field :experience_3_duration %><br />

  <%= f.label :experience_3_description %>:
  <%= f.text_area :experience_3_description %><br />

<%= f.label :experience_4 %>:
    <%= f.text_field :experience_4 %><br />

  <%= f.label :experience_4_position %>:
  <%= f.text_field :experience_4_position %><br />

  <%= f.label :experience_4_duration %>:
  <%= f.text_field :experience_4_duration %><br />

  <%= f.label :experience_4_description %>:
  <%= f.text_area :experience_4_description %><br />

  <%= f.label :skills_description %>:
  <%= f.text_area :skills_description %><br />

  <%= f.submit %>
  <% end %>

app/views/resumes/show.html.erb
<h1>Resumes#show</h1>
<p>Find me in app/views/resumes/show.html.erb</p>

app/views/resumes/update.html.erb
<h1>Resumes#update</h1>
<p>Find me in app/views/resumes/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit your profile:</h1>

    <%= form_for @user do |f| %>
        <%= @user.id %>

            <label for="inputEmail">email</label>
            <%= f.email_field :email %>

            <label for="inputPW">password</label>
            <%= f.password_field :password %>

            <button type="submit" class="btn btn-primary">Edit Profile</button>
    <% end %>

app/views/users/index.html.erb
<h1>List of Users</h1>
<p>This page won't exist once we're up and running, but it's here for the time being.</p>



<ul>
    <% @users.each do |user| %>
        <li><%= user.email %></li>
        <li><%= user.id %></li>
        <li><%= link_to "edit", edit_user_path(user) %></li>
        <li><%= link_to "delete user", user, method: :destroy %></li>
        <li><%= link_to "resumes", user_resumes_path(user) %></li>
        <hr>
    <% end %>
</ul>

<%= link_to "sign up", signup_path %>

app/views/users/new.html.erb
<div class="bgMain">

    <div class="bgColor">
    </div>

    <div class="btn btn-lg btn-primary bgSignin" data-toggle="modal" data-target="#myModal">Sign in</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Please sign in:</h4>
      </div>

      <!-- Sign in for modal body -->
      <div class="modal-body">
        <%= form_for(:session, url: "/login") do |f| %>
            <%= f.email_field :email, class: "form-control input-lg", placeholder: "email"%> <br />
            <%= f.password_field :password, class: "form-control input-lg", placeholder: "password" %>
      </div>
      <!-- Submit for modal body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Sign in", class: "btn btn-primary" %>
      </div>
        <% end %>
    </div>
  </div>
</div>

    <div class="bgCenter">
        <h1 id="bgLogo" class="bgH1">epitome</h1>
        <h2 id="bgLogline" class="bgH1">Résumés that don't suck.</h2>
        <br>
        <div id="bgLogin">
            <%= form_for @user, :html => {class: 'form-inline'} do |f|%>
                <div class="form-group">
                  <%= f.email_field :email, class: "form-control input-lg", placeholder: "email"%>
                </div>
                <div class="form-group">
                  <%= f.password_field :password, class: "form-control input-lg", placeholder: "password" %>
                </div>
                <div class="form-group">
                  <%= f.password_field :password_confirm, class: "form-control input-lg", placeholder: "confirm password" %>
                </div>
                <button type="submit" class="btn btn-default btn-lg">Sign up</button>
              <% end %>

        </div>
    </div>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/welcome.html.erb
welcome.html.erb